version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: blog-db
    environment:
      POSTGRES_DB: golang_multiuser_blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

  app:
    build: .
    container_name: blog-server
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=golang_multiuser_blog
      - DB_SSLMODE=disable
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - PORT=8080
      - GIN_MODE=release
    depends_on:
      - db
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge